LightBlog/LightBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include("blog.urls")),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('chat/', include('chat.urls')),
    path('comment/', include('comment.urls')),
    url(r'static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

LightBlog/account/urls.py
from django.urls import path
from . import views

# 一定要写这行，否则html中会报 is not a  registered namespace 错误
app_name = 'account'

urlpatterns = [
    # 登录
    path(r'login/', views.account_login,name='account_login'),
    # 登出
    path(r'logout/', views.account_logout,name='account_logout'),
    # 注册
    path(r'register/',views.account_register,name='account_register'),
    # 密码重置
    path(r'setpassword/',views.account_setpassword,name='account_setpassword'),
    # 个人信息查询
    path(r'myinformation/',views.myself,name='my_information'),
    # 个人信息编辑
    path(r'edit_myself/',views.myself_edit,name='edit_myself'),
    # 个人图片上传
    path(r'my-image/', views.my_image, name="my_image"),
    # 获取头像API
    path(r'get_avator/',views.get_avator, name='get_avator'),
    # 用户信息查询
    path(r'author/<path:username>', views.author_info, name='author_info'),
    # 个人信息中心的博客文章的流加载
    path(r'article_page/<path:username>', views.article_page, name="article_page"),
]

LightBlog/article/urls.py
from django.urls import path,re_path
from . import views
from . import list_views

app_name = 'article'

urlpatterns = [
    # 文章栏目
    path(r'article_column/', views.article_column, name='article_column'),
    # 文章栏目的重命名
    path('rename_article_column/', views.rename_article_column, name="rename_article_column"),
    # 删除栏目
    path('del_article_column/', views.del_article_column, name="del_article_column"),
    # 文章发布
    path('article_post/',views.article_post,name="article_post"),
    # 个人后台管理的文章列表
    path('article_list',views.article_list,name="article_list"),
    # 个人后台管理的文章查看
    re_path('article_detail/(?P<id>\d+)/', views.article_detail, name="article_detail"),
    # 删除文章
    path('del-article/', views.del_article, name="del_article"),
    # 修改文章
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    # 博客首页
    path('list_article_titles/',list_views.article_titles,name="article_titles"),
    # 博客页面
    path('article_content/<int:article_id>/',list_views.article_content,name="article_content"),
    # 博客评论的流加载
    path('article_comment/<int:article_id>/',list_views.comment_page, name="comment_page"),
    # 博客的点赞
    path('like_article/',views.like_article,name="like_article"),
    # 博客首页的流加载
    path('article_page/',list_views.article_page, name="article_page"),
    # 评论的点赞功能
    path('comment_like/',list_views.comment_like, name='comment_like'),
    # 评论的删除功能
    path('comment_delete',list_views.comment_delete, name='comment_delete')
]

LightBlog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path(r'',views.blog_list, name="blog_list"),
    path(r'<int:article_id>/', views.blog_detail, name="blog_detail")
]

LightBlog/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    # 聊天室
    path('',views.chat, name='chat'),
]

LightBlog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 评论的回复
    path(r'comment_reply', views.comment_reply, name="comment_reply"),
    # 评论的删除
    path(r'comment_reply_delete', views.comment_reply_delete, name="comment_reply_delete"),
    # 评论查看回复
    path(r'comment_reply/get',views.comment_reply_get, name="comment_reply_get"),
    # 个人消息页面
    path(r'message', views.message, name="message"),
    # 博客评论消息的流加载
    path(r'notifications', views.notifications, name="notifications"),
    # 个人消息是否查看的API
    path(r'is_read_comments', views.is_read_comments, name="is_read_comments"),
    # 评论的评论的消息
    path(r'notifications/comments', views.comments, name="comments"),
]

LightBlog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/article_titles.css' %}">
    <link rel="stylesheet" href="{% static 'css/article_comment.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/layui.css' %}">
    <link rel="stylesheet" href="{% static 'css/ImgCropping.css' %}">
    <link rel="stylesheet" href="{% static 'css/cropper.min.css' %}">
    <script src="{% static 'js/cropper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layui.js' %}"></script>
    <link rel="shortcut icon" href="/media/avator/favicon.ico" />
</head>
<body>
{% include "header.html" %}
<div style="padding-bottom:100px">
    {% if request.user.username %}
        <input class="username" type="hidden" value="{{ request.user.username }}">
        {% else %}
        <input class="username" type="hidden">
        {% endif %}
    {% block content %} {% endblock %}
</div>
{% include "footer.html" %}
{% block javascript %} {% endblock %}
</body>
</html>

LightBlog/templates/footer.html
<div style="bottom:0;position:fixed;width:100%;background:white;padding-bottom:30px">
    <hr>
    <p style="text-align:center">© Copyright LFBlog</p>
</div>

LightBlog/templates/header.html
{% load staticfiles %}
<ul class="layui-nav" >
  <li class="layui-nav-item">
    <a href="{% url 'article:article_titles' %}">博客首页<span class="layui-badge">9</span></a>
  </li>
  <li class="layui-nav-item">
    <a href="{% url 'chat:chat' %}">聊天室<span class="layui-badge-dot"></span></a>
  </li>
  <li class="layui-nav-item" lay-unselect="" style="float:right">
    <a href="javascript:;"><img id="avator" src="/media/avator/1554199336240.jpg" class="layui-nav-img avator">{{ request.user.username }}</a>
    <dl class="layui-nav-child">
        {% if request.session.username %}
      <dd><a href="{% url 'account:my_information' %}">个人信息</a></dd>
      <dd><a href="{% url 'comment:message' %}">我的消息<span class="layui-badge read-comments-all" style="display:none"></span></a></dd>
      <dd><a href="{% url 'account:edit_myself' %}">完善信息</a></dd>
      <dd><a href="{% url 'account:account_setpassword' %}">修改密码</a></dd>
      <dd><a href="{% url 'article:article_column' %}">后台管理</a></dd>
      <dd><a href="{% url 'account:account_logout' %}">退出登录</a></dd>
        {% else %}
        <dd><a href="{% url 'account:account_login' %}">登录</a></dd>
        <dd><a href="{% url 'account:account_register' %}">注册</a></dd>
        {% endif %}
    </dl>
  </li>
</ul>

<script>

    layui.use('element', function(){
  		var element = layui.element; //导航的hover效果、二级菜单等功能，需要依赖element模块

  		//监听导航点击
  		element.on('nav(demo)', function(elem){
    	//console.log(elem)
    	layer.msg(elem.text());
  		});
	});

	$(function(){
	    username = $('.username').val()
	    if(username){
	        $('.avator').attr('src','/media/avator/'+username+'.jpg?'+Math.random())
            $.get('/comment/is_read_comments', function(e){
                res = JSON.parse(e)
                nums = res.nums
                commented_nums = res.commented_nums
                if(nums+commented_nums != 0){
                    $('.read-comments-all').css('display','inline-block')
                    $('.read-comments-all').text(nums+commented_nums)
                    $('.read-comments').css('display','block')
                    $('.read-comments').text(nums)
                    $('.read-commented').css('display','block')
                    $('.read-commented').text(commented_nums)
                }
            })
	    }else{
	        $('.avator').attr('src','/media/avator/1554199336240.jpg?'+Math.random())
	    }
	})



</script>

LightBlog/templates/paginator.html
<div class="pagination">
    <span class="step-links">
        {% if current_page.has_previous %}
        <a href="?page={{ current_page.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in current_page.paginator.page_range %}
            {% if num == current_page.number %}
                <span class="selected">{{ current_page.number }}</span>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if current_page.has_next %}
        <a href="?page={{ current_page.next_page_number }}">Next</a> {% endif %}
    </span>
</div>