uploadimg/ajax_img/urls.py
from django.urls import path
from . import views

app_name='ajax_img'

urlpatterns = [
    path('', views.index_view, name='index_view')
]

uploadimg/cropper_img/urls.py
from django.urls import path
from . import views

app_name='cropper_img'

urlpatterns=[
    path('',views.index_views,name="index_views")
]

uploadimg/uploadimg/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('ajax_img/', include('ajax_img.urls')),
    path('cropper_img/',include('cropper_img.urls')),
]

uploadimg/user/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.urls import path
from .views import *

urlpatterns = [
    path('', IndexView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploadimg/user/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    # 使用validators.FileExtensionValidator来进行限制：
    # myfile = models.FileField(upload_to="%Y/%m/%d/", validators=[validators.FileExtensionValidator(['txt', 'pdf'],
 	#       message='myfile必须为txt,pdf格式的文件')])
    # 直接使用ImageField，就可以限制上传的文件，必须是图片，不用再使用验证器validators了，效果都是一样的
    # 如果想要使用ImageField，必须要安装Pillow库，如果没安装运行pip install Pillow安装
    myfile = models.ImageField(upload_to="%Y/%m/%d/")

uploadimg/user/forms.py
from django import forms  # 注意是django下的forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        error_messages = {
            'myfile': {
                'invalid_image': '请上传正确格式的图片！'
            }

        }

uploadimg/ajax_img/views.py
from django.shortcuts import render,HttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.
@csrf_exempt
def index_view(request):
    if request.method == 'GET':
        return render(request, 'ajax_index.html', {'username':'Test5.jpg'})
    else:
        filename = request.POST.get('filename')
        file = request.FILES.get('file')
        # 文件保存路径
        fname = '{}/ajax_img/{}'.format(settings.MEDIA_ROOT,filename)
        try:
            with open(fname, 'wb') as f:
                for c in file.chunks():
                    f.write(c)
            return HttpResponse(json.dumps({'status': 200, 'tips': '上传成功'}))
        except:
            return HttpResponse(json.dumps({'status':404,'tips':'上传失败'}))

uploadimg/cropper_img/views.py
from django.shortcuts import render,HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
import json

# Create your views here.
@csrf_exempt
def index_views(request):
    if request.method == "GET":
        return render(request, 'cropper_img.html')
    else:
        uploadimg = request.FILES.get('uploadimg','')
        img_name = request.POST.get('img_name','')
        fname = '{}/cropper_img/{}'.format(settings.MEDIA_ROOT, img_name)
        try:
            with open(fname,'wb') as f:
                for c in uploadimg.chunks():
                    f.write(c)
            return HttpResponse(json.dumps({'status':200,'tips':'上传成功'}))
        except:
            return HttpResponse(json.dumps({'status':500,'tips':'上传失败'}))

uploadimg/user/views.py
from django.http import HttpResponse
from django.shortcuts import render

from django.views.generic import View
from .forms import ArticleForm


class IndexView(View):
    # 如果是GET请求，直接渲染到上传文件页面
    def get(self, request):
        return render(request, 'index.html')

    # 如果是POST请求，那么将接收文件的值
    def post(self, request):
        # 获取前台传来的文件，request.POST用来接收title和content，request.FILES用来接收文件
        form = ArticleForm(request.POST, request.FILES)
        # 将数据保存到数据库
        if form.is_valid():
            img = form.cleaned_data
            print(img['title'],img['content'],img['myfile'])
            form.save()
            return HttpResponse("SUCCESS")
        else:
            # 打印错误信息
            print(form.errors.get_json_data())
            return HttpResponse("Fail")

uploadimg/ajax_img/templates/ajax_index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>Ajax上传图片</title>
    <link rel="stylesheet" href="{% static 'css/ajax_index.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ajax_index.js' %}"></script>
</head>
<body>
    <div class="file-box">
        <input type="file" name="file" id="input_file" accept="image/gif,image/jpeg,image/jpg,image/png,image/svg" onchange="imgPreview(this, 0)">
    </div>
    <button type="button" class="btn btn-primary img_submit" onclick="post_img()">上传</button>

</body>

<script type="text/javascript">
function post_img(){
    var file = document.getElementById('input_file').files[0];
    var formData = new FormData();
    formData.append('file', $('#input_file')[0].files[0]);
    formData.append('filename', file.name);
    $.ajax({
        url: "{% url 'ajax_img:index_view' %}",
        type: "post",
        data: formData,
        processData: false,
        contentType: false,
        success: function(e){
            info = JSON.parse(e);
            console.log(info.status)
            if(info.status=='200'){
                layer.msg(info.tips);
            }else{
                layer.msg(info.tips)
            }
        }
    });
}
</script>
</html>

uploadimg/cropper_img/templates/cropper_img.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>基于cropper.js的图片裁剪</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="format-detection" content="telephone=no">

    <link rel="stylesheet" href="{% static 'css/cropper.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ImgCropping.css' %}">

</head>
<body style="background: #eee">

<button id="replaceImg" style="margin-right:10px" class="l-btn">更换图片</button>
<button id="uploadImg" class="l-btn">上传图片</button>
<div style="width: 320px;height: 320px;border: solid 1px #555;padding: 5px;margin-top: 10px">
    <img id="finalImg" src="" width="100%">
</div>


<!--图片裁剪框 start-->
<div style="display: none" class="tailoring-container">
    <div class="black-cloth" onclick="closeTailor(this)"></div>
    <div class="tailoring-content">
            <div class="tailoring-content-one">
                <label title="上传图片" for="chooseImg" class="l-btn choose-btn">
                    <input type="file" accept="image/jpg,image/jpeg,image/png" name="file" id="chooseImg" class="hidden" onchange="selectImg(this)">
                    选择图片
                </label>
                <div class="close-tailoring"  onclick="closeTailor(this)">×</div>
            </div>
            <div class="tailoring-content-two">
                <div class="tailoring-box-parcel">
                    <img id="tailoringImg">
                </div>
                <div class="preview-box-parcel">
                    <p>图片预览：</p>
                    <div class="square previewImg"></div>
                    <div class="circular previewImg"></div>
                </div>
            </div>
            <div class="tailoring-content-three">
                <button class="l-btn cropper-reset-btn">复位</button>
                <button class="l-btn cropper-rotate-btn">旋转</button>
                <button class="l-btn cropper-scaleX-btn">换向</button>
                <button class="l-btn sureCut" id="sureCut">确定</button>
            </div>
        </div>
</div>
<!--图片裁剪框 end-->


<script src="{% static 'js/jquery-2.1.1.js' %}"></script>
<script src="{% static 'js/cropper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script>

    //弹出框水平垂直居中
    (window.onresize = function () {
        var win_height = $(window).height();
        var win_width = $(window).width();
        if (win_width <= 768){
            $(".tailoring-content").css({
                "top": (win_height - $(".tailoring-content").outerHeight())/2,
                "left": 0
            });
        }else{
            $(".tailoring-content").css({
                "top": (win_height - $(".tailoring-content").outerHeight())/2,
                "left": (win_width - $(".tailoring-content").outerWidth())/2
            });
        }
    })();

    //弹出图片裁剪框
    $("#replaceImg").on("click",function () {
        $(".tailoring-container").toggle();
    });
    //图像上传
    function selectImg(file) {
        if (!file.files || !file.files[0]){
            return;
        }
        var reader = new FileReader();
        reader.onload = function (evt) {
            var replaceSrc = evt.target.result;
            //更换cropper的图片
            $('#tailoringImg').cropper('replace', replaceSrc,false);//默认false，适应高度，不失真
        }
        reader.readAsDataURL(file.files[0]);
    }
    //cropper图片裁剪
    $('#tailoringImg').cropper({
        aspectRatio: 1/1,//默认比例
        preview: '.previewImg',//预览视图
        guides: true,  //裁剪框的虚线(九宫格)
        autoCropArea: 0.5,  //0-1之间的数值，定义自动剪裁区域的大小，默认0.8
        movable: false, //是否允许移动图片
        dragCrop: true,  //是否允许移除当前的剪裁框，并通过拖动来新建一个剪裁框区域
        movable: true,  //是否允许移动剪裁框
        resizable: true,  //是否允许改变裁剪框的大小
        zoomable: true,  //是否允许缩放图片大小
        mouseWheelZoom: true,  //是否允许通过鼠标滚轮来缩放图片
        touchDragZoom: true,  //是否允许通过触摸移动来缩放图片
        rotatable: true,  //是否允许旋转图片
        crop: function(e) {
            // 输出结果数据裁剪图像。
        }
    });
    //旋转
    $(".cropper-rotate-btn").on("click",function () {
        $('#tailoringImg').cropper("rotate", 45);
    });
    //复位
    $(".cropper-reset-btn").on("click",function () {
        $('#tailoringImg').cropper("reset");
    });
    //换向
    var flagX = true;
    $(".cropper-scaleX-btn").on("click",function () {
        if(flagX){
            $('#tailoringImg').cropper("scaleX", -1);
            flagX = false;
        }else{
            $('#tailoringImg').cropper("scaleX", 1);
            flagX = true;
        }
        flagX != flagX;
    });

    //裁剪后的处理
    $("#sureCut").on("click",function () {
        if ($("#tailoringImg").attr("src") == null ){
            return false;
        }else{
            var cas = $('#tailoringImg').cropper('getCroppedCanvas');//获取被裁剪后的canvas
            var base64url = cas.toDataURL('image/png'); //转换为base64地址形式
            //console.log(base64url);
            $("#finalImg").prop("src",base64url);//显示为图片的形式

            //关闭裁剪框
            closeTailor();
        }
    });
    //关闭裁剪框
    function closeTailor() {
        $(".tailoring-container").toggle();
    }

    $('#uploadImg').on('click',function(){
        var uploadimg = $('#finalImg').attr("src");
        //console.log(uploadimg);
        if(!uploadimg){
            layer.alert('请选择图片', {
                icon: 0,
                closeBtn: 0,
                skin: 'layer-ext-moon', 
                time: 5000,//该皮肤由layer.seaning.com友情扩展。关于皮肤的扩展规则，去这里查阅
                btn: ['明白了','知道了']
            },function(){
                layer.msg('明白就好',{icon: 1});
            });
        }else{
            bs64 = uploadimg.split(',')[1];
            var binary = atob(bs64);
            var array = [];
            for (var i = 0; i < binary.length; i++) {
                array.push(binary.charCodeAt(i));
            }
            var blob =  new Blob([new Uint8Array(array)], {type: 'image/jpeg'});
            //使用FormData()进行ajax请求，上传图片
            var formdata = new FormData()
            //图片名称
            var img_name = new Date().getTime()+'.jpg';
            formdata.append('uploadimg',blob);
            formdata.append('img_name',img_name);
            $.ajax({
                url: "{% url 'cropper_img:index_views' %}",
                type: 'POST',
                data: formdata,
                dataType: 'json',
                processData: false,
                contentType: false,
                success: function(e){
                    if(e['status']=='200'){
                        layer.msg(e['tips']);
                    }else if(e['status'=='500']){
                        layer.msg(e['tips']);
                    }
                }
            })
        }
        
    })

</script>

</body>
</html>

uploadimg/user/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文件上传页</title>
</head>
<body>

<!--{#enctype="multipart/form-data"文件编码方式，必须设置，否则文件无法上传#}-->
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="text" name="content">
    <input type="file" name="myfile">
    <input type="submit" value="提交">
</form>

</body>
</html>