LightBlog/LightBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include("blog.urls")),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('chat/', include('chat.urls')),
    path('comment/', include('comment.urls')),
    url(r'static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

LightBlog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path(r'',views.blog_list, name="blog_list"),
    path(r'<int:article_id>/', views.blog_detail, name="blog_detail")
]

LightBlog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 评论的回复
    path(r'comment_reply', views.comment_reply, name="comment_reply"),
    # 评论的删除
    path(r'comment_reply_delete', views.comment_reply_delete, name="comment_reply_delete"),
    # 评论查看回复
    path(r'comment_reply/get',views.comment_reply_get, name="comment_reply_get"),
    # 个人消息页面
    path(r'message', views.message, name="message"),
    # 博客评论消息的流加载
    path(r'notifications', views.notifications, name="notifications"),
    # 个人消息是否查看的API
    path(r'is_read_comments', views.is_read_comments, name="is_read_comments"),
    # 评论的评论的消息
    path(r'notifications/comments', views.comments, name="comments"),
]

LightBlog/comment/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from article.models import Comment,ArticlePost


# Create your models here.
class Comment_reply(models.Model):
    comment_reply = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="comment_reply")
    reply_type = models.IntegerField(default=0)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentator_reply")
    commented_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commented_user", blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)
    body = models.TextField()
    reply_comment = models.IntegerField(default=0)
    is_read = models.IntegerField(default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {} on {}".format(self.comment_user, self.created)

LightBlog/comment/views.py
from django.shortcuts import render,HttpResponse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST,require_http_methods,require_GET
from article.models import Comment
from .models import Comment_reply
import json
import math


# Create your views here.
@csrf_exempt
@require_POST
def comment_reply(request):
    reply_type = request.POST.get('reply_type','')
    if reply_type == '0':
        id = request.POST.get('id','')
        body = request.POST.get('body','')
        if body.strip() == '':
            return HttpResponse(json.dumps({'code':201,'tips':'内容不能为空'}))
        else:
            try:
                comment = Comment.objects.get(id=id)
                user = request.user
                if user == comment.commentator:
                    return HttpResponse(json.dumps({'code':202,'tips':'别搞我'}))
                Com = Comment_reply(comment_reply=comment, comment_user=user, commented_user=comment.commentator, body=body)
                Com.save()
                comment_info = {'from': user.username,'to':comment.commentator.username , 'id': Com.id, 'body': Com.body,
                                'created': Com.created.strftime("%Y-%m-%d %H:%M:%S")}
                return HttpResponse(json.dumps({'code':203, 'tips':'评论成功', 'res':comment_info}))
            except:
                return HttpResponse(json.dumps({"code": 501, "tips": "评论系统出现错误"}))
    else:
        comment_id = request.POST.get('comment_id','')
        id = request.POST.get('id', '')
        body = request.POST.get('body', '')
        if body.strip() == '':
            return HttpResponse(json.dumps({'code':201,'tips':'内容不能为空'}))
        else:
            try:
                comment = Comment.objects.get(id=comment_id)
                comment_reply = Comment_reply.objects.get(id=id)
                user = request.user
                if user == comment_reply.comment_user:
                    return HttpResponse(json.dumps({'code':202,'tips':'别搞我'}))
                Com = Comment_reply(comment_reply=comment, reply_type=1, comment_user=user, reply_comment=id, commented_user=comment_reply.comment_user, body=body)
                Com.save()
                comment_info = {'from': user.username, 'to': comment_reply.comment_user.username, 'id': Com.id, 'body': Com.body,
                                'created': Com.created.strftime("%Y-%m-%d %H:%M:%S")}
                return HttpResponse(json.dumps({'code': 203, 'tips': '评论成功', 'res': comment_info}))
            except:
                return HttpResponse(json.dumps({"code": 501, "tips": "评论系统出现错误"}))


## 评论删除
@csrf_exempt
@require_POST
def comment_reply_delete(request):
    id = request.POST.get('id','')
    comment_reply = Comment_reply.objects.get(id=id)
    try:
        if request.user == comment_reply.comment_user:
            comment_reply.delete()
            return HttpResponse(json.dumps({'code':201,'tips':'评论已删除'}))
        else:
            return HttpResponse(json.dumps({'code':502,'tips':'You do not have permission...'}))
    except:
        return HttpResponse(json.dumps({'code':203,'tips':'Something error...'}))


def init_data(data):
    items = data.comment_reply.all()
    list_data = []
    for item in items:
        if item.reply_type == 0:
            list_data.append({'from': item.comment_user.username,'to':data.commentator.username , 'id': item.id, 'body': item.body,
                            'created': item.created.strftime("%Y-%m-%d %H:%M:%S")})
        else:
            to_id = item.reply_comment
            list_data.append(
                {'from': item.comment_user.username, 'to': Comment_reply.objects.get(id=to_id).comment_user.username, 'id': item.id, 'body': item.body,
                 'created': item.created.strftime("%Y-%m-%d %H:%M:%S")})
    return list_data


@csrf_exempt
@require_POST
def comment_reply_get(request):
    id = request.POST.get('id','')
    comment = Comment.objects.get(id=id)
    comment_root = {'id':comment.id, 'commentator': comment.commentator.username,'created': comment.created.strftime("%Y-%m-%d %H:%M:%S"), 'comment_like': comment.comment_like.count(), 'body': comment.body}
    comment_child = init_data(comment)
    length = len(comment_child)
    return HttpResponse(json.dumps({'code':201,'comment_root': comment_root, 'comment_child': comment_child, 'nums':length}))


@login_required(login_url='/account/login/')
def message(request):
    return render(request, 'comment/notifications.html')


@require_GET
def notifications(request):
    page = request.GET.get('page', 1)
    try:
        page = int(page)
    except:
        page = 1
    user = request.user
    articles = user.article_post.all()
    response = []
    for article in articles:
        comments = article.comments.all()
        for comment in comments:
            comment.is_read = 1
            comment.save()
            if user == comment.commentator:
                continue
            response.append({'commentator':comment.commentator.username, 'article_title': article.title, 'time': comment.created.strftime("%Y-%m-%d %H:%M:%S"), 'body': comment.body[:50], 'comment_root_id': comment.id, 'article_id': article.id})
    response.sort(key=lambda x: x['time'], reverse=True)
    nums = math.ceil(len(response)/6.0)
    if page > nums:
        page = nums
    res = response[6*(page-1):6*page]
    return HttpResponse(json.dumps({'code':201, 'res':res, 'nums':nums}))


@require_GET
def is_read_comments(request):
    user = request.user
    articles = user.article_post.all()
    count = 0
    for article in articles:
        comments = article.comments.all()
        for comment in comments:
            if user == comment.commentator:
                comment.is_read = 1
                comment.save()
                continue
            elif comment.is_read == 0:
                count += 1
    commented_comments = user.commented_user.all()
    commented_count = 0
    for comment in commented_comments:
        if comment.is_read == 0:
            commented_count += 1
    return HttpResponse(json.dumps({'code':201, 'nums':count, 'commented_nums': commented_count}))


@login_required(login_url='/account/login/')
@require_GET
def comments(request):
    user = request.user
    commenteds = user.commented_user.all()
    res = []
    for comment in commenteds:
        comment.is_read = 1
        comment.save()
        res.append({'commentator': comment.comment_user.username, 'article_title': comment.comment_reply.article.title, 'time': comment.created.strftime("%Y-%m-%d %H:%M:%S"), 'body': comment.body[:50],'comment_root_id': comment.comment_reply.id, 'comment_child_id': comment.id, 'article_id': comment.comment_reply.article.id})
    res.sort(key=lambda x: x['time'], reverse=True)
    return render(request, 'comment/comments.html', {'comments': res})

LightBlog/templates/comment/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/layui.css' %}">
    <link rel="stylesheet" href="{% static 'css/article_comment.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layui.js' %}"></script>
</head>
<body>
<div>
    {% include 'header.html' %}
    <div  class="content" style="margin:10px 10px 100px 10px">
        {% if request.user %}
        <input class="username" type="hidden" value="{{ request.user.username }}">
        {% else %}
        <input class="username" type="hidden">
        {% endif %}
    <div class="layui-col-md2">
        {% include 'comment/leftslider.html' %}
    </div>
    <div class="layui-col-md10" style="padding-bottom:100px">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    </div>
</div>
</body>
</html>

LightBlog/templates/comment/comments.html
{% extends 'comment/base.html' %}
{% load staticfiles %}
{% block title %} 消息 - LightBlog {% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/comment/comment.css' %}">
<div>
    <div class="menu"><h1>收到的评论</h1></div>
    <div class="main">
        <ul id="flow_notifications">
            {% for comment in comments %}
                <li comment_id="{{ comment.comment_root_id }}">
                    <div class="commentator-root"></div>
                                    <div class="commentator commentator-child" id="comment-child-{{ comment.comment_child_id }}" onmouseenter="EnterFunction(this)" onmouseleave="LeaveFunction(this)">
                        <div class="commentator-img">
                            <a href="/account/author/{{ comment.commentator }}">
                                <img src="/media/avator/{{ comment.commentator }}.jpg" class="layui-nav-img" alt="">
                            </a>
                        </div>
                        <div class="commentator-info">
                            <a href="/account/author/{{ comment.commentator }}" class="commentator-name">{{ comment.commentator }}</a>
                            <span style="margin-left:30px">在文章</span>
                            <a href="/article/article_content/{{ comment.article_id }}">《{{ comment.article_title }}》</a>
                            <span> 评论了你</span>
                            <span style="margin-left:20px">{{ comment.time }}</span>
                        </div>
                        <div class="comment-wrap">
                            <pre>{{ comment.body }}</pre>
                        </div>
                        <div class="meta">
                            <a href="javascript:void(0)" comment_id="{{ comment.comment_root_id }}" class="comment_show comment-tool"><span><i class="layui-icon layui-icon-dialogue"></i> <span class="tool-text">查看回复</span></span></a>
                            <a href="javascript:void(0)" comment_id="{{ comment.comment_child_id }}" class="comment_reply comment-tool" onclick="comment_reply(this)"><span><i class="layui-icon layui-icon-reply-fill"></i> <span class="tool-text tool-reply">回 复</span></span></a>
                        </div>
                        <div class="reply_input" comment_id="{{ comment.comment_child_id }}"></div>
                    </div>
                                </li>
            {% empty %}
            <h3>莫得评论</h3>
            {% endfor %}
        </ul>
    </div>
</div>
<script src="{% static 'js/comment/comment.js' %}"></script>
<script>
	function EnterFunction(e){
        $(e).find('.comment-tool').css('display','block');
    }

    function LeaveFunction(e){
        $(e).find('.comment-tool').css('display','none');
    }

    var is_reply = 0; // 判断是否回复

    function comment_reply(e){
        if(is_reply==0){
            var name = $(e).parent().prevAll('.commentator-info:first').find('.commentator-name').text()
            $(e).find('.tool-reply').text('取消回复');
            $(e).parent().next().html('<textarea id="textarea" placeholder="回复 '+name+'"></textarea><div style="position:relative;height:40px"><div style="position:absolute;right:10px;display:block"><button class="layui-btn comment-reply-btn">send</button></div></div>')
            is_reply = 1;
        }else{
            $(e).find('.tool-reply').text('回 复');
            $(e).parent().next().html('');
            is_reply = 0;
        }
    }

    $('body').on('click', '.comment-reply-btn', function(e){
        if($('.username').val()==''){
            layer.msg('请先登录')
        }else{
            var dom = $(this).parent().parent().parent();
            if(dom.parent().hasClass('commentator-root')){
                data = {'reply_type': 0,'id': dom.attr('comment_id'), 'body': dom.children("#textarea").val()}
            }else if(dom.parent().hasClass('commentator-child')){
                data = {'reply_type': 1, 'comment_id': dom.parent().parent().attr('comment_id'), 'id':dom.attr('comment_id'), 'body': dom.children("#textarea").val()}
            }else{
                layer.msg('别搞我呀..');
                return;
            }
            console.log(data)
            $.ajax({
                url: "{% url 'comment:comment_reply' %}",
                method: "POST",
                dataType: "json",
                data: data,
                success: function(res){
                    if(res.code=='203'){
                        console.log(res.res)
                        layer.msg(res.tips);
                        dom.html('')
                        //console.log(dom)
                        dom.prev().find(".tool-reply").text('回 复')
                        data = res.res
                        item = '<div class="commentator commentator-child" id="comment-child-'+data.id+'" onmouseenter="EnterFunction(this)" onmouseleave="LeaveFunction(this)">'+
                        '<div class="commentator-img">'+
                            '<a href="/account/author/'+data.from+'">'+
                                '<img src="/media/avator/'+data.from+'.jpg" class="layui-nav-img" alt="">'+
                            '</a>'+
                        '</div>'+
                        '<div class="commentator-info">'+
                            '<a href="/account/author/'+data.from+'" class="commentator-name">'+data.from+'</a>'+
                            '<span style="margin:0 10px">回复</span>'+
                            '<a href="/account/author/'+data.to+'">'+data.to+'</a>'+
                            '<span style="margin-left:20px">'+ data.created+'</span>'+
                        '</div>'+
                        '<div class="comment-wrap">'+
                            '<pre>'+data.body+'</pre>'+
                        '</div>'+
                        '<div class="meta">'+
                            '<a href="javascript:void(0)" onclick="comment_reply_delete('+data.id+', this)" class="comment-tool comment-delete"><span><i class="layui-icon layui-icon-delete"></i> <span>删 除</span></span></a>'+
                        '</div>'+
                        '<div class="reply_input" comment_id="'+data.id+'"></div>'+
                    '</div>'
                        dom.parent().parent().find('.commentator-root').after($(item))
                        is_reply = 0;
                    }else{
                        layer.msg(res.tips);
                    }
                }
            })
        }

    })


    $('body').on("click", ".comment_show", function(e){
        id = $(this).attr('comment_id')
        $.ajax({
            url: "{% url 'comment:comment_reply_get' %}",
            method: "POST",
            data: {'id': id},
            dataType: "json",
            success: function(res){
                console.log(res)
                if(res.code=='201'){
                    comment_root = res.comment_root
                    console.log(comment_root)
                    comment_child = res.comment_child
                    console.log(comment_child)
                    if('{{request.user.username}}' == comment_root.commentator){
                        item = '<li comment_id="'+comment_root.id+'">'+
                    '<div class="commentator commentator-root" id="comment-root-'+comment_root.id+'" onmouseenter="EnterFunction(this)" onmouseleave="LeaveFunction(this)">'+
                        '<div class="commentator-img">'+
                            '<a href="/account/author/'+comment_root.commentator+'">'+
                                '<img src="/media/avator/'+comment_root.commentator+'.jpg" class="layui-nav-img" alt="">'+
                            '</a>'+
                        '</div>'+
                        '<div class="commentator-info">'+
                            '<a href="/account/author/'+comment_root.commentator+'" class="commentator-name">'+comment_root.commentator+'</a>'+
                            '<span style="margin-left:20px">'+ comment_root.created+'</span>'+
                            '<span style="margin-left:20px"> 人气值: <span class="support-comment">'+comment_root.comment_like+'</span></span>'+
                        '</div>'+
                        '<div class="comment-wrap">'+
                            '<pre>'+comment_root.body+'</pre>'+
                        '</div>'+
                        '<div class="meta">'+
                        '</div>'+
                        '<div class="reply_input" comment_id="'+comment_root.id+'"></div>'+
                    '</div>'+init_comment(comment_child)+
                    '</li>'
                    }else{
                        item = '<li comment_id="'+comment_root.id+'">'+
                    '<div class="commentator commentator-root" id="comment-root-'+comment_root.id+'" onmouseenter="EnterFunction(this)" onmouseleave="LeaveFunction(this)">'+
                        '<div class="commentator-img">'+
                            '<a href="/account/author/'+comment_root.commentator+'">'+
                                '<img src="/media/avator/'+comment_root.commentator+'.jpg" class="layui-nav-img" alt="">'+
                            '</a>'+
                        '</div>'+
                        '<div class="commentator-info">'+
                            '<a href="/account/author/'+comment_root.commentator+'" class="commentator-name">'+comment_root.commentator+'</a>'+
                            '<span style="margin-left:20px">'+ comment_root.created+'</span>'+
                            '<span style="margin-left:20px"> 人气值: <span class="support-comment">'+comment_root.comment_like+'</span></span>'+
                        '</div>'+
                        '<div class="comment-wrap">'+
                            '<pre>'+comment_root.body+'</pre>'+
                        '</div>'+
                        '<div class="meta">'+
                            '<a href="javascript:void(0)" comment_id="'+comment_root.id+'" class="comment_reply comment-tool" onclick="comment_reply(this)"><span><i class="layui-icon layui-icon-reply-fill"></i> <span class="tool-text tool-reply">回 复</span></span></a>'+
                            '<a href="javascript:void(0)" onclick="comment_report()" class="comment-tool comment-report"><span><i class="layui-icon layui-icon-release"></i> <span>举 报</span></span></a>'+
                        '</div>'+
                        '<div class="reply_input" comment_id="'+comment_root.id+'"></div>'+
                    '</div>'+init_comment(comment_child)+
                    '</li>'
                    }
                    layer.open({
                        title: '查看对话',
                        type: 1,
                        skin: 'layui-layer-rim', //加上边框
                        area: ['420px', '85%'], //宽高
                        content: item,
                    });
                }
            }
        })

    })
</script>
{% endblock %}

LightBlog/templates/comment/leftslider.html
<ul class="layui-nav layui-nav-tree layui-bg-cyan layui-inline">
  <li class="layui-nav-item notifications" data-id="1"><a href="{% url 'comment:message' %}"><i class="layui-icon layui-icon-dialogue"></i> 评论 <span class="layui-badge read-comments" style="margin-left:60px;display:none"></span></a></li>
  <li class="layui-nav-item notifications" data-id="2"><a href="{% url 'comment:comments' %}"><i class="layui-icon layui-icon-reply-fill"></i> 回复 <span class="layui-badge read-commented" style="margin-left:60px;display:none"></span></a></li>
  <li class="layui-nav-item notifications" data-id="3"><a href="javascript:void(0)"><i class="layui-icon layui-icon-help"></i> 其他消息</a></li>
</ul>