LightBlog/LightBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views import static
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include("blog.urls")),
    path('account/', include('account.urls')),
    path('article/', include('article.urls')),
    path('chat/', include('chat.urls')),
    path('comment/', include('comment.urls')),
    url(r'static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}, name='media')
]

LightBlog/article/urls.py
from django.urls import path,re_path
from . import views
from . import list_views

app_name = 'article'

urlpatterns = [
    # 文章栏目
    path(r'article_column/', views.article_column, name='article_column'),
    # 文章栏目的重命名
    path('rename_article_column/', views.rename_article_column, name="rename_article_column"),
    # 删除栏目
    path('del_article_column/', views.del_article_column, name="del_article_column"),
    # 文章发布
    path('article_post/',views.article_post,name="article_post"),
    # 个人后台管理的文章列表
    path('article_list',views.article_list,name="article_list"),
    # 个人后台管理的文章查看
    re_path('article_detail/(?P<id>\d+)/', views.article_detail, name="article_detail"),
    # 删除文章
    path('del-article/', views.del_article, name="del_article"),
    # 修改文章
    path('redit-article/<int:article_id>/', views.redit_article, name="redit_article"),
    # 博客首页
    path('list_article_titles/',list_views.article_titles,name="article_titles"),
    # 博客页面
    path('article_content/<int:article_id>/',list_views.article_content,name="article_content"),
    # 博客评论的流加载
    path('article_comment/<int:article_id>/',list_views.comment_page, name="comment_page"),
    # 博客的点赞
    path('like_article/',views.like_article,name="like_article"),
    # 博客首页的流加载
    path('article_page/',list_views.article_page, name="article_page"),
    # 评论的点赞功能
    path('comment_like/',list_views.comment_like, name='comment_like'),
    # 评论的删除功能
    path('comment_delete',list_views.comment_delete, name='comment_delete')
]

LightBlog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path(r'',views.blog_list, name="blog_list"),
    path(r'<int:article_id>/', views.blog_detail, name="blog_detail")
]

LightBlog/article/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class ArticleColumn(models.Model):
    user = models.ForeignKey(User,related_name='article_column',on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticlePost(models.Model):
    author = models.ForeignKey(User,related_name='article_post',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn,on_delete=models.CASCADE,related_name='article_column')
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User,related_name="users_like",blank=True)

    class Meta:
        ordering = ("-updated",)
        index_together = (("id","slug"),)

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, on_delete=models.CASCADE, related_name="comments")
    commentator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentator")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    comment_like = models.ManyToManyField(User, related_name="comment_like", blank=True)
    is_read = models.IntegerField(default=0)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {} on {}".format(self.commentator,self.created)

LightBlog/article/forms.py
from django import forms
from .models import ArticleColumn,ArticlePost

class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ('column',)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body')

LightBlog/article/views.py
from django.shortcuts import render,HttpResponse,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User
from .models import ArticleColumn,ArticlePost
from .forms import ArticleColumnForm,ArticlePostForm
from django.core.paginator import PageNotAnInteger,Paginator,EmptyPage
import json


# Create your views here.
@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    user = request.user
    if request.method == 'GET':
        columns = ArticleColumn.objects.filter(user=user)
        # column_form = ArticleColumnForm()
        return render(request,'article/article_column.html',locals())
    if request.method == 'POST':
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user=user,column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=user,column=column_name)
            return HttpResponse('1')


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login/')
@csrf_exempt
def article_post(request):
    user = request.user
    if request.method == 'POST':
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = user
                new_article.column = user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse('1')
            except:
                return HttpResponse('2')
        else:
            return HttpResponse('3')
    else:
        article_post_form = ArticlePostForm()
        article_columns = user.article_column.all()
        return render(request,'article/article_post.html',locals())


@login_required(login_url='/account/login/')
def article_list(request):
    user = User.objects.get(username=request.session.get('username',''))
    articles_list = ArticlePost.objects.filter(author=user)
    paginator = Paginator(articles_list, 6)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request,'article/article_list.html',locals())


@login_required(login_url='/account/login/')
def article_detail(request, id):
    article = get_object_or_404(ArticlePost, id=id)
    user = request.user
    if user.username != article.author.username:
        return HttpResponse('You do not have permission!')
    return render(request, "article/article_detail.html", locals())


@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    article = ArticlePost.objects.get(id=article_id)
    user = request.user
    if user.username != article.author.username:
        return HttpResponse('You do not have permission!')
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    article = ArticlePost.objects.get(id=article_id)
    user = request.user
    if user.username != article.author.username:
        return HttpResponse('You do not have permission!')
    if request.method == "GET":
        article_columns = user.article_column.all()
        # this_article_form = ArticlePostForm(initial={"title": article.title})
        this_article_column = article.column
        return render(request, "article/redit_article.html",
                      {"article": article, "article_columns": article_columns, "this_article_column": this_article_column})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def like_article(request):
    user = request.user
    article_id = request.POST.get('id','')
    action = request.POST.get('action')
    if article_id and action:
        try:
            article = ArticlePost.objects.get(id=article_id)
            article_likes = article.users_like.all()
            if action == 'like':
                for item in article_likes:
                    if item == user:
                        return HttpResponse(json.dumps({'static':200,'tips':'不能重复点┗|｀O′|┛ 嗷~~~，亲[呕]^-^'}))
                article.users_like.add(user)
                num = article.users_like.count()
                return HttpResponse(json.dumps({'static':201,'tips':'感谢您的喜爱','num':num,'user':user.username}))
            else:
                article.users_like.remove(user)
                num = article.users_like.count()
                return HttpResponse(json.dumps({'static':202,'tips':'我会努力的', 'num':num,'user':user.username}))
        except:
            return HttpResponse(json.dumps({'static':500,'tips':'系统错误,重新尝试'}))

LightBlog/templates/article/article_column.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %} 文章栏目 {% endblock %}
{% block content %}
<div>
    <p class="text-right">
        <button id="add_column" onclick="add_column()" class="layui-btn layui-btn-normal">add column</button>
    </p>
    <div class="columns-table">
  <table class="layui-table"  lay-even="" lay-skin="nob">
    <colgroup>
      <col class="layui-col-xs4">
      <col class="layui-col-xs4">
      <col class="layui-col-xs4">
    </colgroup>
    <thead>
      <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody>
      {% for column in columns %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ column.column }}</td>
            <td>
                <a name="edit" class="edit_btn" href="javascript:" onclick="edit_column(this, {{ column.id }})"> <i class="layui-icon layui-icon-edit" style="color: #1E9FFF;"></i> 编辑</a>
                <a name="delete"class="edit_btn"  href="javascript:" onclick="del_column(this, {{ column.id }})"><span class="layui-icon layui-icon-delete" style="margin-left:20px;">删除</span></a>
            </td>
        </tr>
        {% empty %}
        <p>还没有设置栏目，太懒了。</p>
        {% endfor %}
    </tbody>
  </table>
</div>
</div>



<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    $('.edit_btn').hover(function(){
        $(this).toggleClass('btn-hover');
    })

    function add_column() {
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "新增栏目",
            content: '<div class="layui-form-item" style="margin:45px 40px 0 0;"><label class="layui-form-label">请输入栏目</label><div class="layui-input-block"><input type="text" name="article_column" id="id_column" lay-verify="article_column" autocomplete="off" placeholder="请输入栏目名" class="layui-input"></div></div>',
            btn: ['确定', '取消'],
            yes: function (index, layero) {
                column_name = $('#id_column').val();
                $.ajax({
                    url: '{% url "article:article_column" %}',
                    type: 'POST',
                    data: { "column": column_name },
                    success: function (e) {
                        if (e == "1") {
                            parent.location.reload();
                            layer.msg("good");
                        } else {
                            layer.msg("此栏目已有，请更换名称")
                        }
                    },
                });
            },
            btn2: function (index, layero) {
                layer.close(index);
            }
        });
    }

    function edit_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        var index = layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "编辑栏目",
            content: '<div class="layui-form-item" style="margin:45px 40px 0 0;"><label class="layui-form-label">请输入栏目</label><div class="layui-input-block"><input type="text" name="new_name" id="new_name" lay-verify="new_name" autocomplete="off" placeholder="请输入新的栏目名" class="layui-input" value="'+name+'"></div></div>',
            btn:['确定', '取消'],
            yes: function(index, layero){
                new_name = $("#new_name").val();
                $.ajax({
                    url: "{% url 'article:rename_article_column' %}",
                    type: "POST",
                    data: {"column_id": column_id, "column_name": new_name},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("good");
                        }else{
                            layer.msg("新的名称没有保存,修改失败。")
                        }
                    },
                });
            },
        });
    }

    function del_column(the, column_id){
        var name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除栏目",
            content: '<div style="margin:45px 0 0 30px;font-weight:400;font-size:16px"><p>是否确定删除 '+name+' 栏目</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article_column" %}',
                    type:"POST",
                    data: {"column_id":column_id},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("has been deleted.");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }
</script>
{% endblock %}

LightBlog/templates/article/article_detail.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %} 文章预览 {% endblock %}
{% block content %}
<div>
    <header>
        <h1>{{ article.title }}</h1>
        <p>{{ user.username }}</p>
    </header>

    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
    <div id='editormd-view'>
        <textarea id="append-test" style="display:none;">
{{ article.body }}
        </textarea>
    </div>
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript">
$(function(){
    editormd.markdownToHTML("editormd-view", {
        htmlDecode: "style, script, iframe",
        emoji: true,
        taskList:true,
        tex:true,
        flowChart:true,
        sequenceDiagram : true,
    });
});

</script>
{% endblock %}

LightBlog/templates/article/article_list.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %} 文章列表 {% endblock %}
{% block content %}
<div>
    <div class="columns-table">
  <table class="layui-table"  lay-even="" lay-skin="nob">
    <colgroup>
      <col class="layui-col-xs1">
      <col class="layui-col-xs4">
      <col class="layui-col-xs4">
      <col class="layui-col-xs3">
    </colgroup>
    <thead>
      <tr>
            <td>序号</td>
            <td>标题</td>
            <td>栏目</td>
            <td>操作</td>
        </tr>
    </thead>
    <tbody>
      {% for article in articles %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'article:article_detail' article.id %}">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td>
                <a name="edit" href="{% url 'article:redit_article' article.id %}"><span class="glyphicon glyphicon-pencil">编辑</span></a>
                <a nane="delete" href="javascript:" onclick="del_article(this, {{ article.id }})"><span class="glyphicon glyphicon-trash" style="margin-left:20px;">删除</span></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>
    {% include "paginator.html" %}
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
    function del_article(the, article_id){
        var article_name = $(the).parents("tr").children("td").eq(1).text();
        layer.open({
            type: 1,
            skin: "layui-layer-rim",
            area: ["400px", "200px"],
            title: "删除文章",
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除《'+article_name+'》</p> </div>',
            btn:['确定', '取消'], yes: function(){
                $.ajax({
                    url: '{% url "article:del_article" %}',
                    type:"POST",
                    data: {"article_id":article_id},
                    success: function(e){
                        if(e=="1"){
                            parent.location.reload();
                            layer.msg("has been deleted.");
                        }else{
                            layer.msg("删除失败");
                        }
                    },
                })
            },
        });
    }

</script>
{% endblock %}

LightBlog/templates/article/article_post.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %} 文章发布 {% endblock %}
{% block content %}

<div style="margin-left:10px">
    <form class="layui-form" action="." method="post">{% csrf_token %}
        <div class="layui-form-item">
                        <label class="layui-form-label">文章标题</label>
                        <div class="layui-input-inline">
                            <input type="text" id="id_title" name="article_title" lay-verify="title" placeholder="请输入文章标题" autocomplete="off" class="layui-input">
                        </div>
                            <div class="layui-form-mid layui-word-aux">请输入文章的标题</div>
                    </div>
        <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">文章栏目</label>
                        <div class="layui-input-inline">
                        <select name="modules" id="which_column" lay-verify="required" lay-search="">
                            <option value="">选择栏目</option>
                            {% for column in article_columns %}
                            <option value="{{column.id}}">{{column.column}}</option>


                            {% endfor %}
                        </select>
                        </div>
                    </div>
                </div>

        <div class="row" style="margin-top: 10px;">
            <div class="col-md-2 text-right"><span>内容:</span></div>
            <div id="editormd" class="">
                <textarea style="display:none;" id="id_body"></textarea>
            </div>
        </div>
                <div class="layui-form-item">
                    <div class="layui-input-block">
                    <input type="button" class="layui-btn layui-btn-normal" value="发布" onclick="publish_article()">
                    <button type="reset" class="layui-btn layui-btn-primary" onclick="reset_btn()">重置</button>
                    </div>
                </div>
    </form>
</div>

<script type="text/javascript">
layui.use('form');

function reset_btn(){
    layer.alert('内容', {
  icon: 1,
  skin: 'layer-ext-moon',
  content: '只能重置标题和栏目'
})
};

function publish_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val();
    var body = $("#id_body").val();
    var article_tags = [];
    $.each($("input[name='article_tag']:checked"), function(){article_tags.push($(this).val());});
    $.ajax({
        url: "{% url 'article:article_post' %}",
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id, "tags":JSON.stringify(article_tags)},
        success: function(e){
            if(e=="1"){
                //layer.msg("successful");
                location.href = "{% url 'article:article_list' %}";//修改后：文章发布成功后跳转到文章列表
            }else if(e=="2"){
                layer.msg("sorry.") ;
            }else{
                layer.msg("项目名称必须写，不能空。");
            }
        },
    });
}

</script>
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript">
    $(function() {
        var editor = editormd("editormd", {
            width : "100%",
            height : 640,
            syncScrolling : "single",
            path : "{% static 'editor/lib/' %}"
        });
    });
</script>
{% endblock %}

LightBlog/templates/article/article_titles.html
{% extends "base.html" %}
{% load article_tags %}
{% load staticfiles %}
{% block title %} 博客首页 {% endblock %}
{% block content %}

<div class="container">
    <h1>丰富头脑，善化行为</h1>
    <p>There are {% total_articles %}  articles which you can read.</p>

    <div class="article_ranking" style="margin:20px 40px">
        <h3>最受欢迎文章</h3>
        <ol>
            {% for article in most_viewed %}
            <li><a href="{% url 'article:article_content' article.id %}">{{ forloop.counter }}. {{ article.title }}</a></li>
            {% endfor %}
        </ol>
    </div>

    <!--{% for article in articles %}-->
    <!--<div class="list-group">-->
        <!--<a href="{% url 'article:article_content' article.id %}" class="list-group-item active">-->
            <!--<h3 class="list-group-item-heading">{{article.title}}</h3>-->
        <!--</a>-->
        <!--<p class="list-group-item-text">作者:{{article.author.username}}</p>-->
        <!--<p class="list-group-item-text">概要:{{article.body|slice:'70'| linebreaks}}</p>-->
    <!--</div>-->
    <!--{% endfor %}-->
    <!--{% include "paginator.html" %}-->
    <ul id="flow_demo" ></ul>

<script type="text/javascript">
	layui.use(['layer','flow'],function(){
		var layer = layui.layer;
		var flow = layui.flow;

		flow.load({
			elem: "#flow_demo",
			is_Auto:true,
			end: "emm,nothing next",
			is_Lazyimg: true,
			done: function(page,next){
				var lis = '';
				$.get('/article/article_page/?page='+page, function(e){
				    parse_res = JSON.parse(e)
                    res = parse_res.data
                    page_num = parse_res.page_num
                    console.log(res)
				    for(var i = 0; i < res.length; i++){

                        var item = '<div class="list-group">'+
                            '<a href="/article/article_content/'+res[i].id+'" class="list-group-item active">'+
                                '<h3 class="list-group-item-heading">'+res[i].title+'</h3>'+
                            '</a>'+
                            '<p class="list-group-item-text">作者:'+res[i].author+'</p>'+
                            '<p class="list-group-item-text">概要:'+res[i].body+'</p>'+
                            '<p class="meta"><span><i class="layui-icon layui-icon-praise"></i> '+res[i].users_like+'</span>'+
                            '<span class="update_time">'+res[i].updated+'</span>'+
                            '</p>'+
                        '</div>';

                        lis+=item;

				    }
				    next(lis,page<page_num)
				})


			}
		})
	})
</script>
</div>
{% endblock %}

LightBlog/templates/article/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <style>
        .btn_hover{
            color:"#1E9FFF";
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'css/layui.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layui.js' %}"></script>
    <link rel="shortcut icon" href="/media/avator/favicon.ico" />
</head>
<body>
<div>
    {% include 'header.html' %}
    <div  class="content" style="margin:10px 10px 100px 10px">
        {% if request.user %}
        <input class="username" type="hidden" value="{{ request.user.username }}">
        {% else %}
        <input class="username" type="hidden">
        {% endif %}
    <div class="layui-col-md2">
        {% include 'article/leftslider.html' %}
    </div>
    <div class="layui-col-md10" style="padding-bottom:100px">
        {% block content %}
        {% endblock %}
    </div>
    {% include 'footer.html' %}
    </div>
</div>
</body>
</html>

LightBlog/templates/article/leftslider.html
<ul class="layui-nav layui-nav-tree layui-bg-cyan layui-inline" lay-filter="demo">
  <li class="layui-nav-item"><a href="{% url 'article:article_column'%}">栏目管理</a></li>
  <li class="layui-nav-item"><a href="{% url 'article:article_post' %}">发布文章</a></li>
  <li class="layui-nav-item"><a href="{% url 'article:article_list' %}">文章列表</a></li>
</ul>

LightBlog/templates/article/redit_article.html
{% extends "article/base.html" %}
{% load staticfiles %}
{% block title %} 文章修改 {% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
<div class="container">
    <div class="layui-col-md10" style="padding-bottom:100px">
        <div style="margin-left:10px">
            <form class="layui-form" action="." method="post">{% csrf_token %}

                <div class="layui-form-item">
                        <label class="layui-form-label">文章标题</label>
                        <div class="layui-input-inline">
                            <input type="text" id="id_title" name="article_title" lay-verify="title" placeholder="请输入文章标题" autocomplete="off" class="layui-input" value="{{article.title}}">
                        </div>
                            <div class="layui-form-mid layui-word-aux">请输入文章的标题</div>
                    </div>

                <div class="layui-form-item">
                    <div class="layui-inline">
                        <label class="layui-form-label">文章栏目</label>
                        <div class="layui-input-inline">
                        <select name="modules" id="which_column" lay-verify="required" lay-search="">
                            {% for column in article_columns %}
                            {% if column == this_article_column %}
                            <option value="{{column.id}}" selected="">{{column.column}}</option>
                            {% else %}
                            <option value="{{column.id}}">{{column.column}}</option>

                            {% endif %}
                            {% endfor %}
                        </select>
                        </div>
                    </div>
                </div>

                <div class="layui-row" style="margin-top: 10px;">
                    <div id="editormd" class="layui-col-md10 text-left">
                        <!--{{article_post_form.body}}-->
                        <textarea style="display:none;" id="id_body">
{{article.body}}
                </textarea>
                    </div>
                </div>

                <div class="layui-form-item">
                    <div class="layui-input-block">
                    <input type="button" class="layui-btn layui-btn-normal" value="发布" onclick="redit_article()">
                    <button type="reset" class="layui-btn layui-btn-primary" onclick="reset_btn()">重置</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript" src='{% static "js/jquery.js" %}'></script>
<script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
<script type="text/javascript">
$(function() {
    var editor = editormd("editormd", { 
        width : "100%",
        height : 640,
        //syncScrolling : "single",
        path : "{% static 'editor/lib/' %}", 
    });
}); 

layui.use('form');

</script>

<script type="text/javascript">

function reset_btn(){
    layer.alert('内容', {
  icon: 1,
  skin: 'layer-ext-moon',
  content: '只能重置标题和栏目'
})
};

function redit_article(){
    var title = $("#id_title").val();
    var column_id = $("#which_column").val(); 
    var body = $("#id_body").val();
    $.ajax({
        url: "{% url 'article:redit_article' article.id %}", 
        type: "POST",
        data: {"title":title, "body":body, "column_id":column_id}, 
        success: function(e){
            if(e=="1"){ 
                layer.msg("successful");
                location.href = "{% url 'article:article_list' %}"; 
            }else{
                layer.msg("sorry."); 
            }
        }, 
    });
}

</script>


{% endblock %}